# React Dockerfile

# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

COPY vehicle-detection-frontend/package*.json ./

# Install dependencies
RUN npm install

COPY vehicle-detection-frontend .

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
